In [43]:
# DSC 550
# Week 4
# Assignment 4.2
# Aaron Kuethe

# Install Packages

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import json
import string
import unicodedata
import sys
import nltk

In [44]:
# 1. Load the data file DailyComments.csv from the Week 4 Data Files into a data frame.

# Reading in the DailyComments csv file.

daily = pd.read_csv("DailyComments.csv")
daily

Day of Week                                        comments
0      Monday                             Hello, how are you?
1     Tuesday                            Today is a good day!
2   Wednesday  It's my birthday so it's a really special day!
3    Thursday       Today is neither a good day or a bad day!
4      Friday                           I'm having a bad day.
5    Saturday       There' s nothing special happening today.
6      Sunday                      Today is a SUPER good day!

In [45]:
# 2.Identify a scheme to categorize each comment as positive or negative. You can devise your own scheme or find a commonly used
# scheme to perform this sentiment analysis. However you decide to do this, make sure to explain the scheme you decide to use.

# The scheme I am going to go with for categorizing each comment will be to look at each word individually using the
# CountVectorizer function. Then I will identify words in each comment that have a positive or negative connotation, such as
# 'good' or 'bad', and assign those words points that will help to identify the overall sentiment of each comment.

In [46]:
# 3. Implement your sentiment analysis with code and display the results. Note: DailyComments.csv is a purposely small file, so 
# you will be able to clearly see why the results are what they are.

# Importing CountVectorizer

corpus = daily['comments']

from sklearn.feature_extraction.text import CountVectorizer



# Creating group of words by using CountVectorizer to pre-process the text data and see which words have a positive or negative
# connotation.

vectorizer = CountVectorizer()
x = vectorizer.fit_transform(corpus)

print("")
print("vectorized words:")
print("")
print(vectorizer.get_feature_names())

# Good, bad, and special are all words that stand out.


vectorized words:

['are', 'bad', 'birthday', 'day', 'good', 'happening', 'having', 'hello', 'how', 'is', 'it', 'my', 'neither', 'nothing', 'or', 'really', 'so', 'special', 'super', 'there', 'today', 'you']


In [47]:
# Creating an array of the data

print("Identify Feature Words - Matrix View:")
print("")
print(x.toarray())


# Displaying the matrix

daily_df = pd.DataFrame({'text' : corpus})

Identify Feature Words - Matrix View:

[[1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 1 1 0 0 0 0 0 0 2 1 0 0 0 1 1 1 0 0 0 0]
 [0 1 0 2 1 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0]
 [0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0]
 [0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0]]


In [48]:
# Assigning points to positive and negative words from the 'comments' column. And then creating a formula to summarize them.

daily_df['positive1'] = daily_df.text.str.count('good')
daily_df['positive2']= daily_df.text.str.count('special')
daily_df['negative'] = daily_df.text.str.count('bad')
daily_df['TotScore'] = daily_df.positive1 + daily_df.positive2 - daily_df.negative

print(daily_df)


# Displaying the total score of the 'comments' column.

Z = sum(daily_df['TotScore'])
print("")
print("Overall Score:  ",Z)

# Based off of this sentiment analysis, the only one that is slightly misleading is on Saturday and line 5. It picks up the
# word 'special' and therefore says it is a positive day. However, the sentiment is nothing special is happening and therefore
# it is a neutral sentiment. I think this goes to show that our results may never be 100% perfect, but more often than not this
# will help us in identifying sentiment. Even if I added 'nothing' as a negative word, it would even the sentiment of this
# articular statement out to make it neutral. However, if there was no positive word in it, it would make the comment sentiment 
# negative which also wouldn't be correct. It is best to leave it alone and live with the results not being 100% accurate.

                                             text  positive1  positive2  \
0                             Hello, how are you?          0          0   
1                            Today is a good day!          1          0   
2  It's my birthday so it's a really special day!          0          1   
3       Today is neither a good day or a bad day!          1          0   
4                           I'm having a bad day.          0          0   
5       There' s nothing special happening today.          0          1   
6                      Today is a SUPER good day!          1          0   

   negative  TotScore  
0         0         0  
1         0         1  
2         0         1  
3         1         0  
4         1        -1  
5         0         1  
6         0         1  

Overall Score:   3
